<a href="https://colab.research.google.com/github/justmadeid/DataMining/blob/main/13091_Tugas3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('Data_Tugas3.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(x)

[['Made' 22.0 1000000.0]
 ['Rizky' 25.0 2800000.0]
 ['Ary' 22.0 750000.0]
 ['Rizky' 21.0 nan]
 ['Made' 23.0 8000000.0]
 ['Ary' 26.0 580000.0]
 ['Rizky' nan 50000.0]
 ['Ary' 24.0 2400000.0]
 ['Rizky' 30.0 7000000.0]
 ['Made' 25.0 15000000.0]]


In [4]:
print(y)

['No' 'Yes' 'No' 'No' 'No' 'Yes' 'No' 'No' 'Yes' 'Yes']


In [5]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [6]:
print(x)

[['Made' 22.0 1000000.0]
 ['Rizky' 25.0 2800000.0]
 ['Ary' 22.0 750000.0]
 ['Rizky' 21.0 4175555.5555555555]
 ['Made' 23.0 8000000.0]
 ['Ary' 26.0 580000.0]
 ['Rizky' 24.22222222222222 50000.0]
 ['Ary' 24.0 2400000.0]
 ['Rizky' 30.0 7000000.0]
 ['Made' 25.0 15000000.0]]


In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [8]:
print(x)

[[0.0 1.0 0.0 22.0 1000000.0]
 [0.0 0.0 1.0 25.0 2800000.0]
 [1.0 0.0 0.0 22.0 750000.0]
 [0.0 0.0 1.0 21.0 4175555.5555555555]
 [0.0 1.0 0.0 23.0 8000000.0]
 [1.0 0.0 0.0 26.0 580000.0]
 [0.0 0.0 1.0 24.22222222222222 50000.0]
 [1.0 0.0 0.0 24.0 2400000.0]
 [0.0 0.0 1.0 30.0 7000000.0]
 [0.0 1.0 0.0 25.0 15000000.0]]


In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [10]:
print(y)

[0 1 0 0 0 1 0 0 1 1]


In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=1)

In [12]:
print(x_train)

[[0.0 0.0 1.0 24.22222222222222 50000.0]
 [0.0 1.0 0.0 23.0 8000000.0]
 [0.0 1.0 0.0 22.0 1000000.0]
 [0.0 0.0 1.0 21.0 4175555.5555555555]
 [0.0 0.0 1.0 25.0 2800000.0]
 [1.0 0.0 0.0 24.0 2400000.0]
 [0.0 0.0 1.0 30.0 7000000.0]
 [1.0 0.0 0.0 26.0 580000.0]]


In [13]:
print(x_test)

[[1.0 0.0 0.0 22.0 750000.0]
 [0.0 1.0 0.0 25.0 15000000.0]]


In [14]:
print(y_train)

[0 0 0 0 1 0 1 1]


In [15]:
print(y_test)

[0 1]


In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [17]:
print(x_train)

[[0.0 0.0 1.0 -0.06965629659606803 -1.1606507852064931]
 [0.0 1.0 0.0 -0.5411758427848319 1.7222153872916481]
 [0.0 1.0 0.0 -0.9269645623938207 -0.8161573432098599]
 [0.0 0.0 1.0 -1.3127532820028096 0.33537746056368134]
 [0.0 0.0 1.0 0.2304015964331458 -0.1634329267951864]
 [1.0 0.0 0.0 -0.15538712317584302 -0.3084827971095583]
 [0.0 0.0 1.0 2.15934519447809 1.3595907115057184]
 [1.0 0.0 0.0 0.6161903160421346 -0.9684597070399503]]


In [18]:
print(x_test)

[[1.0 0.0 0.0 -0.9269645623938207 -0.9068135121563423]
 [0.0 1.0 0.0 0.2304015964331458 4.260588117793156]]
